### ISSUE TITLE
[bug]: Webpage Shows 404 Error on Reload in Development Environment

### ISSUE THREAD

**Issue by SiddhiT28** [chirantanbanik/Wellread#58]
**Describe the bug**
When the webpage is reloaded in the hosted URL, it shows a 404 error page. This issue does not occur on the first load of the page, but only upon subsequent reloads.

**To Reproduce**
1. Open the hosted webpage.
2. Once the page has loaded, hit the reload button or press F5.

**Expected behavior**
The webpage reloads without any issues and displays the correct content.

**Screenshots**
![image](https://github.com/chirantanbanik/Wellread/assets/82750191/95f8bc9b-de54-4a59-8f45-c561f924fc48)

/login route shows 404 when reloaded.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version: 121.1

**Comment by SiddhiT28** [comment]
@chirantanbanik Please assign this issue to me under GSSOC'24

**Comment by Aman0413** [comment]
Hi @chirantanbanik,

I'd like to work on this bug. Please assign it to me.

Thanks,
Aman Verma

**Comment by Debatreya** [comment]
Hi @chirantanbanik 
I'd like to fixed this issue.
I have experienced it before while deploying my projects and I know exactly what solves this.
This issue occurs because React basically makes only Single page Applications.
But when we use react router for navigation, it creates an illusion of moving to another page without reloading.
What actually happens is that the url that changes from (baseURL -> baseURL/page) is not an actual redirect.
When we reload, browser tries to get to baseURL/page but  React being a SPA only knows the baseURL and not baseURL/page hence it gives a not found error. This happens in Production not in localhost.

To solve this we have to add some redirects configurations which are specific to vercel.
Please Assign it to me.

Thanks,
Debatreya.
